pool:
  vmImage: 'Ubuntu 16.04'

variables:
  azureSubscription: 'TE Account - NoBun (6c1f4f3b-f65f-4667-8f9e-b9c48e09cd6b)'
  resourceGroup: infra
  location: westus2
  userObjectId: c345288a-577e-40a5-b36d-c2ca6ff5c796
  baseName: nobun

steps:
- task: AzureCLI@1
  displayName: Create infra resources
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: scriptPath
    scriptPath: deploy.sh
    arguments: '-g $(resourceGroup) -l $(location) -n $(baseName) -u $(userObjectId)'